### ISSUE TITLE
Redis support

### ISSUE THREAD

**Issue by cemo** [Moocar/logback-gelf#40]
I am totally new to GELF land and I would like to evaluate GELF with Logstash. In our scenario our application servers will log their output to Redis. Is there any support for logging to Redis with GELF?

**Comment by alexan** [comment]
I'm also interested in logging against redis. 
Here is another logback appender which supports this behavior. https://github.com/mp911de/logstash-gelf/blob/master/src/site/markdown/redis.md 

Is this appended capable of logging into redis? I'm interested in your implementation because. I'm using https://github.com/gini/dropwizard-gelf which uses this appended.

**Comment by Moocar** [comment]
Yep that appended looks like it does the job. However it's not interoperable with this library. So if you just want a basic appender, I'd go ahead and use it.

**Comment by alexan** [comment]
thanks for your info I forked the the dropwizard-gelf module to use the
other appender allready

2015-07-14 16:37 GMT+02:00 Anthony Marcar <notifications@github.com>:
